name: chatbottomato
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <8.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.7.2
  flutter_spinkit: ^5.2.1
  google_generative_ai: ^0.4.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  provider: ^6.1.2
  uuid: ^4.4.0
  http: ^1.1.0
  http_parser: ^4.0.0
  flutter_launcher_icons: ^0.10.0
dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0

  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
